name: booking_management_app
description: "Restaurant booking and operations management app for Cinnamon Garden"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.15.0
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  lottie: ^2.7.0
  table_calendar: ^3.0.9
  uuid: ^4.4.2
  country_code_picker: ^3.3.0
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  background_color: "#FFFFFF"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/animations/chef.json
    - assets/animations/loader.json
    - assets/images/cinnamon_logo.png
    - assets/images/app_logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
