// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs4ssqPutl2m1-zLjg9ku684m5Cx82rDE',
    appId: '1:608889797638:web:95188c426c03beb185d787',
    messagingSenderId: '608889797638',
    projectId: 'cinnamon-garden-deea9',
    authDomain: 'cinnamon-garden-deea9.firebaseapp.com',
    storageBucket: 'cinnamon-garden-deea9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe1EXl1YCNm-oql08t2RyxynRuyFyPLAo',
    appId: '1:608889797638:android:d173b4b99886183085d787',
    messagingSenderId: '608889797638',
    projectId: 'cinnamon-garden-deea9',
    storageBucket: 'cinnamon-garden-deea9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAWwTKzb3NxaJm99O7UHo_s49i9_Y-4Aw',
    appId: '1:608889797638:ios:b26ee903bb774a0385d787',
    messagingSenderId: '608889797638',
    projectId: 'cinnamon-garden-deea9',
    storageBucket: 'cinnamon-garden-deea9.firebasestorage.app',
    androidClientId: '608889797638-vtk7qd4mvh1ie8qe4i2n6d4qb981q6q0.apps.googleusercontent.com',
    iosBundleId: 'com.tech.booking.bookingManagementApp',
  );
}
